### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by MazenIbrahim1** [MazenIbrahim1/PHAJAM#1]
Navigation bar should include:

- [x] Logo of application = Home
- [x] NEED OUR OWN LOGO THO
- Routes:
- [x] Status page
- [x] Files page
- [x] Explore page
- [x] Peers page
- [x] Settings page

<img width="125" alt="Screenshot 2024-09-21 at 8 11 43 PM" src="https://github.com/user-attachments/assets/b0612226-19b1-412e-a6ae-31d0edc82f94">

**Comment by arpithav1** [comment]
uiupdate has all the new UI & new logo
